version: "3"
services:
  db:
    #image: postgres:latest
    image: pgvector/pgvector:pg17
    command: postgres -c 'max_connections=100'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - pg-net
  # Why redis ?  we just keep it here for now in the future it might we will use it for something elsefor =som paralele quee tasks 
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
networks:
  pg-net:
  redis-net:
volumes:
  db-vector-data:
  redis-data:
